"""baseline schema

Revision ID: 0bd9fd9ff567
Revises: 
Create Date: 2026-06-18 12:32:53.854461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bd9fd9ff567'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators',
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=32), nullable=False),
    sa.Column('nom', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('operator_id')
    )
    op.create_index(op.f('ix_operators_matricule'), 'operators', ['matricule'], unique=True)
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('ref_produit', sa.String(length=64), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_ref_produit'), 'products', ['ref_produit'], unique=True)
    op.create_table('scans',
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('storage_url', sa.String(length=512), nullable=False),
    sa.Column('dpi', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_index(op.f('ix_scans_sha256'), 'scans', ['sha256'], unique=True)
    op.create_table('tools',
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('code_outillage', sa.String(length=64), nullable=False),
    sa.Column('libelle', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('tool_id')
    )
    op.create_index(op.f('ix_tools_code_outillage'), 'tools', ['code_outillage'], unique=True)
    op.create_table('work_orders',
    sa.Column('of_id', sa.Integer(), nullable=False),
    sa.Column('n_of', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('of_id')
    )
    op.create_index(op.f('ix_work_orders_n_of'), 'work_orders', ['n_of'], unique=True)
    op.create_table('fiches',
    sa.Column('fiche_id', sa.Integer(), nullable=False),
    sa.Column('of_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Enum('extrait', 'en_revue', 'valide', name='statut_fiche'), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('raw_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['of_id'], ['work_orders.of_id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('fiche_id')
    )
    op.create_table('audit_log',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('fiche_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=128), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=128), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fiche_id'], ['fiches.fiche_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('controls',
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('fiche_id', sa.Integer(), nullable=False),
    sa.Column('type_controle', sa.Enum('controle_electrique', 'controle_final', 'correspondance_serie', name='type_controle'), nullable=False),
    sa.Column('methode', sa.Enum('manuel', 'banc_de_test', name='methode'), nullable=True),
    sa.Column('resultat', sa.Boolean(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fiche_id'], ['fiches.fiche_id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.operator_id'], ),
    sa.PrimaryKeyConstraint('control_id')
    )
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('fiche_id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['fiche_id'], ['fiches.fiche_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_items_numero_serie'), 'items', ['numero_serie'], unique=False)
    op.create_table('operations',
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('fiche_id', sa.Integer(), nullable=False),
    sa.Column('partie', sa.Enum('p1', 'p2', 'controle', name='partie'), nullable=False),
    sa.Column('nom_operation', sa.String(length=255), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('applicable', sa.Boolean(), nullable=True),
    sa.Column('date_op', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('heure_debut', sa.Time(), nullable=True),
    sa.Column('heure_fin', sa.Time(), nullable=True),
    sa.Column('qte_realisee', sa.Integer(), nullable=True),
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('statut_revue', sa.Enum('auto', 'a_revoir', 'corrige', name='statut_revue'), nullable=True),
    sa.ForeignKeyConstraint(['fiche_id'], ['fiches.fiche_id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.operator_id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.tool_id'], ),
    sa.PrimaryKeyConstraint('operation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operations')
    op.drop_index(op.f('ix_items_numero_serie'), table_name='items')
    op.drop_table('items')
    op.drop_table('controls')
    op.drop_table('audit_log')
    op.drop_table('fiches')
    op.drop_index(op.f('ix_work_orders_n_of'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_tools_code_outillage'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_scans_sha256'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_products_ref_produit'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_operators_matricule'), table_name='operators')
    op.drop_table('operators')
    # ### end Alembic commands ###
    # autogenerate's drop_table doesn't drop the native enum types it created
    # (other tables could share them) — drop them explicitly so upgrade/
    # downgrade is a clean round-trip.
    sa.Enum(name='statut_revue').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='partie').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='methode').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='type_controle').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='statut_fiche').drop(op.get_bind(), checkfirst=True)
